# Generated by Django 2.2.5 on 2019-11-12 09:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trax_vehicle_manager_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivers',
            options={},
        ),
        migrations.CreateModel(
            name='Drivers_Odometer_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers_odometer_data_date_of_entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('drivers_odometer_data_odometer_kilometer', models.CharField(blank=True, max_length=12)),
                ('drivers_odometer_data_cleaner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trax_vehicle_manager_data.Cleaners')),
                ('drivers_odometer_data_driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trax_vehicle_manager_data.Drivers')),
                ('drivers_odometer_data_vehicle_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trax_vehicle_manager_data.Vehicles')),
            ],
            options={
                'verbose_name': "Driver's Odometer",
                'verbose_name_plural': 'Drivers Odometer List',
            },
        ),
    ]
