# Generated by Django 2.2.5 on 2019-11-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trax_vehicle_manager_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diesel',
            name='account_number',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='amount_Rs',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='balance_Rs',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='card_used',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='diesel_rate',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='merchant',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='odometer_reading',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='ownership',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='terminal_id',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='transaction_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='vehicle_detail',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='volume',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
