# Generated by Django 2.2.5 on 2019-11-26 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trax_vehicle_manager_data', '0002_auto_20191123_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diesel',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
