# Generated by Django 2.2.5 on 2019-11-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trax_vehicle_manager_data', '0002_auto_20191112_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers_odometer_data',
            name='drivers_odometer_data_mobile_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
