# Generated by Django 2.2.5 on 2019-11-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trax_vehicle_manager_data', '0003_drivers_odometer_data_drivers_odometer_data_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='driver_aadhar_card_residence_address',
            field=models.CharField(blank=True, default='', max_length=264),
        ),
        migrations.AddField(
            model_name='drivers',
            name='driver_alternate_contact_number',
            field=models.CharField(blank=True, default='', max_length=264),
        ),
        migrations.AddField(
            model_name='drivers',
            name='driver_last_employer_name',
            field=models.CharField(blank=True, default='', max_length=264),
        ),
        migrations.AddField(
            model_name='drivers',
            name='driver_license_residence_address',
            field=models.CharField(blank=True, default='', max_length=264),
        ),
        migrations.AddField(
            model_name='drivers',
            name='driver_years_of_experience',
            field=models.CharField(blank=True, default='', max_length=264),
        ),
        migrations.AddField(
            model_name='drivers',
            name='driver_years_with_kruze_or_aaron',
            field=models.CharField(blank=True, default='', max_length=264),
        ),
    ]
