# Generated by Django 2.2.5 on 2019-12-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trax_vehicle_manager_data', '0003_pucrecurringexpenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilChangeRecurringExpenses',
            fields=[
                ('recurringexpensesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trax_vehicle_manager_data.RecurringExpensesModel')),
                ('last_date_of_oil_change', models.DateTimeField(blank=True)),
                ('actual_km', models.CharField(blank=True, max_length=900)),
                ('minimum_oil_km', models.CharField(blank=True, max_length=900)),
                ('over_km', models.CharField(blank=True, max_length=900)),
            ],
            bases=('trax_vehicle_manager_data.recurringexpensesmodel',),
        ),
    ]
