# Generated by Django 2.2.5 on 2019-11-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trax_vehicle_manager_data', '0004_auto_20191112_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='vehicle_registered_number',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
    ]
