# Generated by Django 2.2.5 on 2019-11-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trax_vehicle_manager_data', '0005_vehicles_vehicle_registered_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_buying_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_card_number',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_current_status',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_id',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_manufacturer',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_ownership',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_ownership_details',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_type',
            field=models.CharField(max_length=900),
        ),
    ]
