# Generated by Django 2.2.5 on 2019-11-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trax_vehicle_manager_data', '0006_auto_20191115_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='incremental_average',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='minimum_average',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_ownership',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_registered_number',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_seating_capacity',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
