# Generated by Django 2.2.5 on 2019-11-20 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trax_vehicle_manager_data', '0007_auto_20191115_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_dealer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=900),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='bill_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
