# Generated by Django 2.2.5 on 2019-11-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trax_vehicle_manager_data', '0010_maintenance_vehicle_ownership_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='vehicle_ownership_name',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='vehicle_ownership_name',
            field=models.CharField(choices=[('ATPL', 'ATPL'), ('AT', 'AT'), ('CT', 'CT')], default='AT', max_length=900),
        ),
    ]
